[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_KEY,SUPABASE_SERVICE_KEY,SUPABASE_URL"

[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions-internal"
