[build]
  command = "pnpm install --shamefully-hoist && pnpm run build"
  publish = ".output/public"
  functions = ".output/server"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--shamefully-hoist=true"
  PNPM_FLAGS = "--shamefully-hoist=true"

# Serverless functions
[functions]
  node_bundler = "esbuild"
  directory = ".output/server"