[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_KEY,SUPABASE_SERVICE_KEY,SUPABASE_URL"

[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "dist/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200